Update tag_and_merge to post a fake comment

diff --git a/.github/actions/asana-log-message/action.yml b/.github/actions/asana-log-message/action.yml
--- a/.github/actions/asana-log-message/action.yml
+++ b/.github/actions/asana-log-message/action.yml
@@ -1,5 +1,5 @@
 name: Add a Log Message to Asana Task
-description: Adds a collaborator to an Asana task
+description: Adds a comment to an Asana task
 inputs:
   access-token:
     description: "Asana access token"
@@ -11,7 +11,11 @@ inputs:
     type: string
   comment:
     description: "Comment to add to the Asana task"
-    required: true
+    required: false
+    type: string
+  template:
+    description: "Path to a template file for the comment (processed by envsubst before being sent to Asana)"
+    required: false
     type: string
 runs:
   using: "composite"
@@ -41,22 +45,110 @@ runs:
           exit 1
         fi
 
+    - id: process-template-payload
+      if: ${{ inputs.template }}
+      shell: bash
+      env:
+        TEMPLATE_PATH: ${{ inputs.template }}
+      run: |
+        if [ ! -f $TEMPLATE_PATH ]; then
+          echo "::error::Template file not found at $TEMPLATE_PATH"
+          exit 1
+        fi
+
+        # Process the template file with envsubst
+        payload="$(envsubst < $TEMPLATE_PATH | yq -o=j | sed -E 's/\\n( *)([^\\n])/\2/g')"
+        echo "payload=$payload" >> $GITHUB_OUTPUT
+
+    - id: process-comment-payload
+      if: ${{ inputs.comment }}
+      shell: bash
+      env:
+        COMMENT: ${{ inputs.comment}}
+        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      run: |
+
+        payload="{ \"data\": { \"text\": \"${COMMENT}\n\nWorkflow URL: ${WORKFLOW_URL}\" } }"
+        echo "payload=$payload" >> $GITHUB_OUTPUT
+
     - id: add-comment
       shell: bash
       env:
         ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
         TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
-        TASK_BODY: ${{ inputs.comment }}
-        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+        TASK_BODY: ${{ steps.process-template-payload.outputs.payload || steps.process-comment-payload.outputs.payload }}
       run: |
         return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/stories" \
           -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
           -H 'content-type: application/json' \
           --write-out '%{http_code}' \
           --output /dev/null \
-          -d "{ \"data\": { \"text\": \"${TASK_BODY}\n\nWorkflow URL: ${WORKFLOW_URL}\" } }")
+          -d "$payload")
 
         if [ $return_code -ne 201 ]; then
           echo "::error::Failed to add a comment to the Asana task"
           exit 1
         fi
+
+# name: Add a Log Message to Asana Task
+# description: Adds a comment to an Asana task
+# inputs:
+#   access-token:
+#     description: "Asana access token"
+#     required: true
+#     type: string
+#   task-url:
+#     description: "Asana release task URL"
+#     required: false
+#     type: string
+#   comment:
+#     description: "Comment to add to the Asana task"
+#     required: true
+#     type: string
+# runs:
+#   using: "composite"
+#   steps:
+#     - id: get-automation-subtask
+#       uses: ./.github/actions/asana-get-release-automation-subtask-id
+#       with:
+#         access-token: ${{ inputs.access-token }}
+#         task-url: ${{ inputs.task-url }}
+
+#     - id: add-colaborator
+#       shell: bash
+#       env:
+#         ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
+#         ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
+#         TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
+#       run: |
+#         return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/addFollowers" \
+#           -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
+#           -H 'content-type: application/json' \
+#           --write-out '%{http_code}' \
+#           --output /dev/null \
+#           -d "{ \"data\": { \"followers\": [ \"${ASSIGNEE_ID}\" ] } }")
+
+#         if [ $return_code -ne 200 ]; then
+#           echo "::error::Failed to add a collaborator to the Asana task"
+#           exit 1
+#         fi
+
+#     - id: add-comment
+#       shell: bash
+#       env:
+#         ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
+#         TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
+#         TASK_BODY: ${{ inputs.comment }}
+#         WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+#       run: |
+#         return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/stories" \
+#           -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
+#           -H 'content-type: application/json' \
+#           --write-out '%{http_code}' \
+#           --output /dev/null \
+#           -d "{ \"data\": { \"text\": \"${TASK_BODY}\n\nWorkflow URL: ${WORKFLOW_URL}\" } }")
+
+#         if [ $return_code -ne 201 ]; then
+#           echo "::error::Failed to add a comment to the Asana task"
+#           exit 1
+#         fi
diff --git a/.github/workflows/tag_and_merge.yml b/.github/workflows/tag_and_merge.yml
--- a/.github/workflows/tag_and_merge.yml
+++ b/.github/workflows/tag_and_merge.yml
@@ -60,88 +60,94 @@ jobs:
 
     - name: Create Tag and GitHub Release
       id: create-tag
-      uses: ./.github/actions/create-tag-and-github-release
-      with:
-        prerelease: true
-        github-token: ${{ github.token }}
-
-    - name: Merge to base branch
-      id: merge
-      uses: actions/github-script@v7
-      with:
-        github-token: ${{ secrets.GHA_ELEVATED_PERMISSIONS_TOKEN }}
-        script: |
-          github.rest.repos.merge({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            base: "${{ env.base-branch }}",
-            head: "${{ env.branch }}"
-          })
-
-    - name: Get Asana automation subtask
-      id: get-automation-subtask
-      if: always()
-      uses: ./.github/actions/asana-get-release-automation-subtask-id
-      with:
-        access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
-        task-url: ${{ env.asana-task-url }}
-
-    - name: Create Asana task on failed merge
-      if: failure()
-      env:
-        ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
-        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
-        TASK_NAME: "Merging ${{ env.branch }} to ${{ env.base-branch }} failed"
-        TASK_BODY: "The ${{ steps.create-tag.outputs.tag }} release has been successfully tagged and published in GitHub releases,
-          but merging to ${{ env.base-branch }} failed. Please resolve conflicts and merge ${{ env.branch }} to ${{ env.base-branch }} manually."
-        TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
-        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
       run: |
-        return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/subtasks" \
-          -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
-          -H 'content-type: application/json' \
-          --write-out '%{http_code}' \
-          --output /dev/null \
-          -d "{
-                \"data\": {
-                  \"name\": \"${TASK_NAME}\",
-                  \"resource_subtype\": \"default_task\",
-                  \"notes\": \"${TASK_BODY}\n\nWorkflow URL: ${WORKFLOW_URL}\",
-                  \"assignee\": \"${ASSIGNEE_ID}\"
-                }
-              }
-          ")
+        echo "tag=0.41.0" >> $GITHUB_OUTPUT
+      # uses: ./.github/actions/create-tag-and-github-release
+      # with:
+      #   prerelease: true
+      #   github-token: ${{ github.token }}
 
-        if [ $return_code -ne 201 ]; then
-          echo "::error::Failed to create Asana task"
-          exit 1
-        fi
+    # - name: Merge to base branch
+    #   id: merge
+    #   uses: actions/github-script@v7
+    #   with:
+    #     github-token: ${{ secrets.GHA_ELEVATED_PERMISSIONS_TOKEN }}
+    #     script: |
+    #       github.rest.repos.merge({
+    #         owner: context.repo.owner,
+    #         repo: context.repo.repo,
+    #         base: "${{ env.base-branch }}",
+    #         head: "${{ env.branch }}"
+    #       })
 
-    - name: Re-add release task owner to Automation task
-      if: success()
-      env:
-        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
-        ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
-        TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
-      run: |
-        return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/addFollowers" \
-          -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
-          -H 'content-type: application/json' \
-          --write-out '%{http_code}' \
-          --output /dev/null \
-          -d "{ \"data\": { \"followers\": [ \"${ASSIGNEE_ID}\" ] } }")
+    # - name: Get Asana automation subtask
+    #   id: get-automation-subtask
+    #   if: always()
+    #   uses: ./.github/actions/asana-get-release-automation-subtask-id
+    #   with:
+    #     access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
+    #     task-url: ${{ env.asana-task-url }}
 
-        if [ $return_code -ne 200 ]; then
-          echo "::error::Failed to add a collaborator to the Asana task"
-          exit 1
-        fi
+    # - name: Create Asana task on failed merge
+    #   if: failure()
+    #   env:
+    #     ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
+    #     ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+    #     TASK_NAME: "Merging ${{ env.branch }} to ${{ env.base-branch }} failed"
+    #     TASK_BODY: "The ${{ steps.create-tag.outputs.tag }} release has been successfully tagged and published in GitHub releases,
+    #       but merging to ${{ env.base-branch }} failed. Please resolve conflicts and merge ${{ env.branch }} to ${{ env.base-branch }} manually."
+    #     TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
+    #     WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+    #   run: |
+    #     return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/subtasks" \
+    #       -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
+    #       -H 'content-type: application/json' \
+    #       --write-out '%{http_code}' \
+    #       --output /dev/null \
+    #       -d "{
+    #             \"data\": {
+    #               \"name\": \"${TASK_NAME}\",
+    #               \"resource_subtype\": \"default_task\",
+    #               \"notes\": \"${TASK_BODY}\n\nWorkflow URL: ${WORKFLOW_URL}\",
+    #               \"assignee\": \"${ASSIGNEE_ID}\"
+    #             }
+    #           }
+    #       ")
+
+    #     if [ $return_code -ne 201 ]; then
+    #       echo "::error::Failed to create Asana task"
+    #       exit 1
+    #     fi
+
+    # - name: Re-add release task owner to Automation task
+    #   if: success()
+    #   env:
+    #     ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+    #     ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
+    #     TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
+    #   run: |
+    #     return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/addFollowers" \
+    #       -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
+    #       -H 'content-type: application/json' \
+    #       --write-out '%{http_code}' \
+    #       --output /dev/null \
+    #       -d "{ \"data\": { \"followers\": [ \"${ASSIGNEE_ID}\" ] } }")
+
+    #     if [ $return_code -ne 200 ]; then
+    #       echo "::error::Failed to add a collaborator to the Asana task"
+    #       exit 1
+    #     fi
 
     - name: Report success
       if: success()
       uses: ./.github/actions/asana-log-message
+      env:
+        branch: ${{ env.branch }}
+        base_branch: ${{ env.base-branch }}
+        dmg_url: ${{ vars.TEST_DMG_URL_ROOT }}duckduckgo-${{ steps.create-tag.outputs.tag }}.dmg
+        release_url: https://github.com/${{ github.repository }}/releases/tag/${{ steps.create-tag.outputs.tag }}
+        tag: ${{ steps.create-tag.outputs.tag }}
       with:
         access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
         task-url: ${{ env.asana-task-url }}
-        comment: "New internal build is ready. Repository is tagged with ${{ steps.create-tag.outputs.tag }} tag.
-          ${{ env.branch }} branch has been sucessfully merged to ${{ env.base-branch }} and GitHub release
-          is created at https://github.com/${{ github.repository }}/releases/tag/${{ steps.create-tag.outputs.tag }}."
+        template: ./.github/assets/internal-release-ready.yml
