Exit with error if the Asana user ID is not found for a GitHub username

diff --git a/.github/actions/asana-create-pr-subtask/action.yml b/.github/actions/asana-create-pr-subtask/action.yml
--- a/.github/actions/asana-create-pr-subtask/action.yml
+++ b/.github/actions/asana-create-pr-subtask/action.yml
@@ -34,4 +34,10 @@ runs:
         env:
           ASANA_ACCESS_TOKEN: ${{ inputs.access-token }}
         run: |
-          ${{ github.action_path }}/asana-create-pr-subtask.sh ${{ inputs.asana-task-id }} ${{ steps.get-asana-user-id.outputs.user-id }} ${{ inputs.github-pr-url }}
+          # If the Asana User ID is not found, exit with an error
+          if [[ -z "${{ steps.get-asana-user-id.outputs.user-id }}" ]]; then
+            echo "Error: Failed to get Asana user ID for GitHub user ${{ inputs.github-reviewer-user }}"
+            exit 1
+          else
+            ${{ github.action_path }}/asana-create-pr-subtask.sh ${{ inputs.asana-task-id }} ${{ steps.get-asana-user-id.outputs.user-id }} ${{ inputs.github-pr-url }}
+          fi
