Migrate send mattermost to fastlane (#3571)
Task/Issue URL: https://app.asana.com/0/0/1208793082476405/f
Tech Design URL:
CC:

**Description**:
- Migrate "Send Mattermost" GHA steps to fastlane action 

**Optional E2E tests**:
- [ ] Run PIR E2E tests
Check this to run the Personal Information Removal end to end tests. If
updating CCF, or any PIR related code, tick this.
- [x] Bump fastlane automation 

**Steps to test this PR**:
1. I commented out parts and tested the [Make Notarized DMG
Release](https://github.com/duckduckgo/macos-browser/actions/runs/11909556567/job/33187209804)

![image](https://github.com/user-attachments/assets/7511f6b1-6cb7-4776-b394-54cee14c1965)
2. Same for [Make App Store Connect
Release](https://github.com/duckduckgo/macos-browser/actions/runs/11910287408)

![image](https://github.com/user-attachments/assets/c250a94c-e6f3-4d35-a3dc-208fb2a248e8)

3. Variants was not tested as it's identical to "Make Notarized DMG
Release", it was tested on the automation side earlier in the week

<!--
Tagging instructions
If this PR isn't ready to be merged for whatever reason it should be
marked with the `DO NOT MERGE` label (particularly if it's a draft)
If it's pending Product Review/PFR, please add the `Pending Product
Review` label.

If at any point it isn't actively being worked on/ready for
review/otherwise moving forward (besides the above PR/PFR exception)
strongly consider closing it (or not opening it in the first place). If
you decide not to close it, make sure it's labelled to make it clear the
PRs state and comment with more information.
-->

**Definition of Done**:

* [ ] Does this PR satisfy our [Definition of
Done](https://app.asana.com/0/1202500774821704/1207634633537039/f)?

---
###### Internal references:
[Pull Request Review
Checklist](https://app.asana.com/0/1202500774821704/1203764234894239/f)
[Software Engineering
Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design
Template](https://app.asana.com/0/59792373528535/184709971311943)
[Pull Request
Documentation](https://app.asana.com/0/1202500774821704/1204012835277482/f)

diff --git a/.github/workflows/build_appstore.yml b/.github/workflows/build_appstore.yml
--- a/.github/workflows/build_appstore.yml
+++ b/.github/workflows/build_appstore.yml
@@ -163,13 +163,9 @@ jobs:
       env:
         WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
         DESTINATION: ${{ env.destination }}
+        PLATFORM: macOS
       run: |
-        export MM_USER_HANDLE=$(base64 -d <<< ${{ secrets.MM_HANDLES_BASE64 }} | jq ".${{ github.actor }}" | tr -d '"')
-
-        if [[ -z "${MM_USER_HANDLE}" ]]; then
-            echo "Mattermost user handle not known for ${{ github.actor }}, skipping sending message"
-        else
-            curl -s -H 'Content-type: application/json' \
-                -d "$(envsubst < ./scripts/assets/appstore-release-mm-template.json | jq ".${{ job.status }}")" \
-                ${{ secrets.MM_WEBHOOK_URL }}
-        fi
+        bundle exec fastlane run mattermost_send_message \
+          mattermost_webhook_url:${{ secrets.MM_WEBHOOK_URL }} \
+          github_handle:${{ github.actor }} \
+          template_name:$([[ "${{ job.status }}" == "success" ]] && echo "public-release-complete" || echo "public-release-failed")
