release to test flight only for app store build

diff --git a/.github/workflows/build_appstore.yml b/.github/workflows/build_appstore.yml
--- a/.github/workflows/build_appstore.yml
+++ b/.github/workflows/build_appstore.yml
@@ -67,6 +67,7 @@ jobs:
 
     steps:
 
+    # # KS: TODO remove _review
     - name: Assert release branch
       if: env.destination == 'appstore'
       run: |
@@ -104,6 +105,7 @@ jobs:
     - name: Select Xcode
       run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer
 
+    # TODO remove _review
     - name: Archive and Upload the App
       env:
         APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
@@ -111,7 +113,7 @@ jobs:
         APPLE_API_KEY_ISSUER: ${{ secrets.APPLE_API_KEY_ISSUER }}
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
       run: |
-        bundle exec fastlane release_${{ env.destination }}
+        bundle exec fastlane release_${{ env.destination }}_review
         dsym_path="${{ github.workspace }}/DuckDuckGo-AppStore.app.dSYM.zip"
         mv -f "${{ github.workspace }}/DuckDuckGo App Store.app.dSYM.zip" "${dsym_path}"
         version="$(cut -d ' ' -f 3 < Configuration/Version.xcconfig)"
@@ -119,49 +121,49 @@ jobs:
         echo "dsym-path=${dsym_path}" >> $GITHUB_ENV
         echo "app-version=${version}.${build_number}" >> $GITHUB_ENV
 
-    - name: Upload dSYMs artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: DuckDuckGo-${{ env.destination }}-dSYM-${{ env.app-version }}
-        path: ${{ env.dsym-path }}
+    # - name: Upload dSYMs artifact
+    #   uses: actions/upload-artifact@v4
+    #   with:
+    #     name: DuckDuckGo-${{ env.destination }}-dSYM-${{ env.app-version }}
+    #     path: ${{ env.dsym-path }}
 
-    - name: Upload dSYMs to S3
-      id: upload-dsyms-to-s3
-      if: ${{ env.upload-to == 's3' }}
-      env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
-        DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.DSYM_BUCKET_PREFIX }}/DuckDuckGo-AppStore-${{ env.app-version }}-dSYM.zip
-      run: |
-        echo "dsym-s3-path=${DSYM_S3_PATH}" >> $GITHUB_OUTPUT
-        aws s3 cp ${{ env.dsym-path }} ${{ env.DSYM_S3_PATH }}
+    # - name: Upload dSYMs to S3
+    #   id: upload-dsyms-to-s3
+    #   if: ${{ env.upload-to == 's3' }}
+    #   env:
+    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+    #     AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
+    #     DSYM_S3_PATH: s3://${{ vars.DSYM_BUCKET_NAME }}/${{ vars.DSYM_BUCKET_PREFIX }}/DuckDuckGo-AppStore-${{ env.app-version }}-dSYM.zip
+    #   run: |
+    #     echo "dsym-s3-path=${DSYM_S3_PATH}" >> $GITHUB_OUTPUT
+    #     aws s3 cp ${{ env.dsym-path }} ${{ env.DSYM_S3_PATH }}
 
-    - name: Report success
-      env:
-        DSYM_S3_PATH: ${{ steps.upload-dsyms-to-s3.outputs.dsym-s3-path }}
-        TAG: ${{ env.app-version }}
-        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
-      run: |
-        bundle exec fastlane run asana_log_message \
-          task_url:"${{ env.asana-task-url }}" \
-          template_name:"debug-symbols-uploaded" \
-          github_handle:"${{ github.actor }}" \
-          is_scheduled_release:"${{ github.event_name == 'schedule' }}"
+    # - name: Report success
+    #   env:
+    #     DSYM_S3_PATH: ${{ steps.upload-dsyms-to-s3.outputs.dsym-s3-path }}
+    #     TAG: ${{ env.app-version }}
+    #     WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+    #     ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+    #   run: |
+    #     bundle exec fastlane run asana_log_message \
+    #       task_url:"${{ env.asana-task-url }}" \
+    #       template_name:"debug-symbols-uploaded" \
+    #       github_handle:"${{ github.actor }}" \
+    #       is_scheduled_release:"${{ github.event_name == 'schedule' }}"
 
-    - name: Send Mattermost message
-      if: success() || failure() # Don't execute when cancelled
-      env:
-        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
-        DESTINATION: ${{ env.destination }}
-      run: |
-        export MM_USER_HANDLE=$(base64 -d <<< ${{ secrets.MM_HANDLES_BASE64 }} | jq ".${{ github.actor }}" | tr -d '"')
+    # - name: Send Mattermost message
+    #   if: success() || failure() # Don't execute when cancelled
+    #   env:
+    #     WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+    #     DESTINATION: ${{ env.destination }}
+    #   run: |
+    #     export MM_USER_HANDLE=$(base64 -d <<< ${{ secrets.MM_HANDLES_BASE64 }} | jq ".${{ github.actor }}" | tr -d '"')
 
-        if [[ -z "${MM_USER_HANDLE}" ]]; then
-            echo "Mattermost user handle not known for ${{ github.actor }}, skipping sending message"
-        else
-            curl -s -H 'Content-type: application/json' \
-                -d "$(envsubst < ./scripts/assets/appstore-release-mm-template.json | jq ".${{ job.status }}")" \
-                ${{ secrets.MM_WEBHOOK_URL }}
-        fi
+    #     if [[ -z "${MM_USER_HANDLE}" ]]; then
+    #         echo "Mattermost user handle not known for ${{ github.actor }}, skipping sending message"
+    #     else
+    #         curl -s -H 'Content-type: application/json' \
+    #             -d "$(envsubst < ./scripts/assets/appstore-release-mm-template.json | jq ".${{ job.status }}")" \
+    #             ${{ secrets.MM_WEBHOOK_URL }}
+    #     fi
