Rename workflows and update references.

diff --git a/.github/workflows/macos_sync_end_to_end.yml b/.github/workflows/macos_sync_end_to_end.yml
--- a/.github/workflows/macos_sync_end_to_end.yml
+++ b/.github/workflows/macos_sync_end_to_end.yml
@@ -1,18 +1,19 @@
-name: macOS - Sync-End-to-End tests MacOS11/12
+name: macOS - Sync End-to-End tests
 
 on:
   workflow_dispatch:
-  # schedule:
-  #   - cron: '0 4 * * *' # run at 4 AM UTC
+  schedule:
+    - cron: '0 5 * * *' # run at 5 AM UTC
 
 jobs:
   create-notarized-app:
-    name: Prepare DMG Release
-    uses: ./.github/workflows/build_notarized.yml
+    name: Build Notarized Review app
+    uses: ./.github/workflows/macos_build_notarized.yml
     with:
       release-type: review
       create-dmg: false
-      branch: ${{ github.ref_name }}
+      branch: ${{ github.sha }}
+      skip-notify: true
     secrets:
       APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}
       APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
@@ -27,20 +28,33 @@ jobs:
       MM_WEBHOOK_URL: ${{ secrets.MM_WEBHOOK_URL }}
       SSH_PRIVATE_KEY_FASTLANE_MATCH: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
 
-  sync-end-to-end-tests-older-macos:
-    name: Sync E2E tests
+  sync-end-to-end-tests:
+    name: Sync End-to-End Tests
     needs: create-notarized-app
-    env:
-      app-version: ${{ needs.create-notarized-app.outputs.app-version }}
-
     runs-on: ${{ matrix.runner }}
     strategy:
       fail-fast: false
       matrix:
-        runner: [ macos-11, macos-12-large ]
+        runner: [macos-13-xlarge, macos-14-xlarge, macos-15-xlarge]
+        include:
+          - xcode-version: "15.2"
+            runner: macos-13-xlarge
+          - xcode-version: "15.4"
+            runner: macos-14-xlarge
+          - xcode-version: "16.2"
+            runner: macos-15-xlarge
 
     timeout-minutes: 60
+
     steps:
+    - name: Install screenresolution
+      if: matrix.runner == 'macos-15-xlarge'
+      run: brew install screenresolution
+
+    - name: Change screen resolution
+      if: matrix.runner == 'macos-15-xlarge'
+      run: screenresolution set 1920x1080x32@60
+
     - name: Register SSH key for certificates repository access
       uses: webfactory/ssh-agent@v0.9.0
       with:
@@ -62,7 +76,6 @@ jobs:
         MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
         SSH_PRIVATE_KEY_FASTLANE_MATCH: ${{ secrets.SSH_PRIVATE_KEY_FASTLANE_MATCH }}
       run: |
-        bundle exec fastlane sync_signing_dmg_review
         bundle exec fastlane sync_signing_ci
 
     - name: Download and unzip artifact
@@ -86,13 +99,11 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-spm-
 
-    - name: Select Xcode 14.2 for macOS 12
-      if: matrix.runner == 'macos-12-large'
-      run: sudo xcode-select -s /Applications/Xcode_14.2.app/Contents/Developer
-
-    - name: Select Xcode 13.2.1 for macOS 11
-      if: matrix.runner == 'macos-11'
-      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app/Contents/Developer
+    - name: Select Xcode
+      run: |
+        # Override .xcode_version because 15.4 is not available on macos 13
+        echo "${{ matrix.xcode-version }}" > .xcode-version
+        sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer
 
     - name: Create test account for Sync and return the recovery code
       uses: duckduckgo/sync_crypto/action@main
@@ -100,62 +111,64 @@ jobs:
       with:
         debug: true
 
-    # This first bit is a hack to stop the app building package dependencies that isn't needed by the test runner
-    - name: Build test runner
+    - name: Build Sync e2e tests
       run: |
-        rm -rf LocalPackages
-        rm -rf /Users/runner/work/macos-browser/macos-browser/DuckDuckGo.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
-        sed -i '' '/\/\* Begin XCSwiftPackageProductDependency section \*\//,/\/\* End XCSwiftPackageProductDependency section \*\//d' DuckDuckGo.xcodeproj/project.pbxproj
-        sed -i '' '/\/\* Begin XCRemoteSwiftPackageReference section \*\//,/\/\* End XCRemoteSwiftPackageReference section \*\//d' DuckDuckGo.xcodeproj/project.pbxproj
         set -o pipefail && xcodebuild build-for-testing \
-          -scheme "SyncE2EUITestsOldVersions" \
+          -scheme "Sync End-to-End UI Tests CI" \
           -derivedDataPath DerivedData \
-          -configuration Review
+          -skipPackagePluginValidation \
+          -skipMacroValidation \
+        | tee xcodebuild.log \
+        | xcbeautify
 
     - name: Unzip and Copy app to /DerivedData
       run: |
         cd DuckDuckGo-review-*.app && unzip DuckDuckGo-*.zip
-        cp -R "DuckDuckGo Review.app" "../DerivedData/Build/Products/Review/DuckDuckGo Review.app"
+        mv -f "DuckDuckGo Review.app" "../DerivedData/Build/Products/Review/DuckDuckGo Review.app"
 
-    - name: Run tests
+    - name: Run UI Tests
       env:
         CODE: ${{ steps.sync-recovery-code.outputs.recovery-code }}
       run: |
-        defaults write com.duckduckgo.macos.browser.review moveToApplicationsFolderAlertSuppress 1
+        # Set CODE environment variable in the scheme definition, since Xcode 15.4 doesn't
+        # seem to recognize global environment variables otherwise.
+        # We use xmlstarlet to edit the scheme XML file.
+        brew install xmlstarlet
+        xmlstarlet ed -i '/Scheme/LaunchAction/EnvironmentVariables/EnvironmentVariable[1]' -t elem -n "EnvironmentVariable" \
+          -i '/Scheme/LaunchAction/EnvironmentVariables/EnvironmentVariable[1]' -t attr -n "key" -v "CODE" \
+          -i '/Scheme/LaunchAction/EnvironmentVariables/EnvironmentVariable[1]' -t attr -n "value" -v "$CODE" \
+          -i '/Scheme/LaunchAction/EnvironmentVariables/EnvironmentVariable[1]' -t attr -n "isEnabled" -v "YES" \
+          "DuckDuckGo.xcodeproj/xcshareddata/xcschemes/Sync End-to-End UI Tests CI.xcscheme" > updated.xcscheme
+        mv -f updated.xcscheme "DuckDuckGo.xcodeproj/xcshareddata/xcschemes/Sync End-to-End UI Tests CI.xcscheme"
+
         defaults write com.duckduckgo.macos.browser.review sync.environment Development
-        defaults write com.duckduckgo.macos.browser.review onboarding.finished -bool true
-        set -o pipefail && xcodebuild test \
-          -scheme "SyncE2EUITestsOldVersions" \
+        defaults write com.duckduckgo.macos.browser.review moveToApplicationsFolderAlertSuppress 1
+        set -o pipefail && xcodebuild test-without-building \
+          -scheme "Sync End-to-End UI Tests CI" \
           -derivedDataPath DerivedData \
-          -configuration Review \
+          -skipPackagePluginValidation \
+          -skipMacroValidation \
           -test-iterations 2 \
           -retry-tests-on-failure \
-        | tee xcodebuild.log \
-        | (if [ "${{ matrix.runner }}" = "macos-11" ]; then
-            xcpretty --report junit --output ui-tests.xml
-          else
-            xcbeautify --report junit --report-path . --junit-report-filename ui-tests.xml
-          fi)
+        | tee -a xcodebuild.log \
+        | tee ui-tests.log
 
- #   - name: Create Asana task when workflow failed
- #     if: ${{ failure() }} && github.ref == 'refs/heads/main'
- #     run: |
- #       curl -s "https://app.asana.com/api/1.0/tasks" \
- #          --header "Accept: application/json" \
- #          --header "Authorization: Bearer ${{ secrets.ASANA_ACCESS_TOKEN }}" \
- #          --header "Content-Type: application/json" \
- #          --data ' { "data": { "name": "GH Workflow Failure - Sync End to end tests", "projects": [ "${{ vars.MACOS_APP_DEVELOPMENT_ASANA_PROJECT_ID }}" ], "notes" : "The end to end workflow has failed. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" } }'
+    - name: Prepare test report
+      if: always()
+      run: |
+        xcbeautify --report junit --report-path . --junit-report-filename ui-tests.xml < ui-tests.log
 
     - name: Publish tests report
       uses: mikepenz/action-junit-report@v4
-      if: always()
+      if: always() # always run even if the previous step fails
       with:
         check_name: "Test Report ${{ matrix.runner }}"
         report_paths: ui-tests.xml
+        check_retries: true
 
     - name: Upload logs when workflow failed
       uses: actions/upload-artifact@v4
-      if: always()
+      if: failure() || cancelled()
       with:
         name: "BuildLogs ${{ matrix.runner }}"
         path: |
@@ -163,3 +176,19 @@ jobs:
           DerivedData/Logs/Test/*.xcresult
           ~/Library/Logs/DiagnosticReports/*
         retention-days: 7
+
+  notify-failure:
+    name: Notify on failure
+    if: ${{ always() && github.event_name == 'schedule' && (needs.sync-end-to-end-tests.result == 'failure' || needs.sync-end-to-end-tests.result == 'cancelled') }}
+    needs: [sync-end-to-end-tests]
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Create Asana task when workflow failed
+      uses: duckduckgo/native-github-asana-sync@v1.1
+      with:
+        action: create-asana-task
+        asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        asana-project: ${{ vars.MACOS_APP_DEVELOPMENT_ASANA_PROJECT_ID }}
+        asana-task-name: GH Workflow Failure - Sync End-to-End Tests
+        asana-task-description: The Sync end-to-end workflow has failed. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
