Update pr_task_url

diff --git a/.github/workflows/pr_task_url.yml b/.github/workflows/pr_task_url.yml
--- a/.github/workflows/pr_task_url.yml
+++ b/.github/workflows/pr_task_url.yml
@@ -5,12 +5,17 @@ on:
     types: [opened, edited, closed]
 
 jobs:
-  check-asana-task-url:
 
-    name: Check Asana Task URL
+  # This job is used to assert that the task linked in the PR description belongs to the specified project (App Board).
+  assert-project-membership:
+
+    name: Check Asana Task Project Membership
 
     runs-on: ubuntu-latest
-    if: github.event.action != 'closed'
+
+    outputs:
+      task_id: ${{ steps.get-task-id.outputs.task_id }}
+      failure: ${{ steps.check-task-url.outputs.failure }}
 
     steps:
     - name: Get Task ID
@@ -40,8 +45,20 @@ jobs:
           echo "failure=1" >> $GITHUB_OUTPUT
         fi
 
+  # If a task is missing from the App Board project, add a comment to the PR and fail the check.
+  # Otherwise, delete the comment and pass the check.
+  report-task-missing-from-project:
+
+    name: Report Asana Task Missing From Project
+
+    runs-on: ubuntu-latest
+    if: github.event.action != 'closed'
+
+    needs: [assert-project-membership]
+
+    steps:
     - name: Comment on the PR
-      if: ${{ steps.check-task-url.outputs.failure == '1' }}
+      if: ${{ needs.assert-project-membership.result.failure == '1' }}
       env:
         ASANA_PROJECT_NAME: ${{ vars.MACOS_APP_BOARD_ASANA_PROJECT_NAME }}
       uses: marocchino/sticky-pull-request-comment@v2
@@ -51,7 +68,7 @@ jobs:
           :no_entry_sign: The Asana task linked in the PR description is not added to ${{ env.ASANA_PROJECT_NAME }} project.
 
     - name: Delete comment on the PR
-      if: ${{ steps.check-task-url.outputs.failure == '0' }}
+      if: ${{ needs.assert-project-membership.result.failure == '0' }}
       uses: marocchino/sticky-pull-request-comment@v2
       with:
         header: asana-task-check-status
@@ -59,8 +76,9 @@ jobs:
     
     - name: Report status
       run: |
-        exit ${{ steps.check-task-url.outputs.failure }}
+        exit ${{ needs.assert-project-membership.result.failure }}
 
+  # When a PR is merged, move the task to the Waiting for Release section of the App Board.
   mark-waiting-for-release:
 
     name: Move to Waiting for Release
@@ -68,24 +86,17 @@ jobs:
     runs-on: ubuntu-latest
     if: github.event.action == 'closed' && github.event.pull_request.merged == true
 
-    steps:
-      - name: Get Task ID
-        id: get-task-id
-        env:
-          BODY: ${{ github.event.pull_request.body }}
-        run: |
-          task_id=$(grep -i "task/issue url.*https://app.asana.com/" <<< "$BODY" \
-            | sed -E 's|.*https://(.*)|\1|' \
-            | cut -d '/' -f 4)
-          echo "task_id=$task_id" >> $GITHUB_OUTPUT
+    needs: [assert-project-membership]
 
-      - name: Move to Waiting for Release
-        env:
-          ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
-          ASANA_PROJECT_ID: ${{ vars.MACOS_APP_BOARD_ASANA_PROJECT_ID }}
-        run: |
-          curl -fLSs -X POST "https://app.asana.com/api/1.0/sections/${{ vars.MACOS_APP_BOARD_WAITING_FOR_RELEASE_SECTION_ID }}/addTask" \
-            -H "Authorization: Bearer ${{ env.ASANA_ACCESS_TOKEN }}" \
-            -H "Content-Type: application/json" \
-            --output /dev/null \
-            -d "{\"data\": {\"task\": \"${{ steps.get-task-id.outputs.task_id }}\"}}"
+    steps:
+    - name: Move to Waiting for Release
+      if: ${{ needs.assert-project-membership.result.failure == '0' }}
+      env:
+        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        ASANA_PROJECT_ID: ${{ vars.MACOS_APP_BOARD_ASANA_PROJECT_ID }}
+      run: |
+        curl -fLSs -X POST "https://app.asana.com/api/1.0/sections/${{ vars.MACOS_APP_BOARD_WAITING_FOR_RELEASE_SECTION_ID }}/addTask" \
+          -H "Authorization: Bearer ${{ env.ASANA_ACCESS_TOKEN }}" \
+          -H "Content-Type: application/json" \
+          --output /dev/null \
+          -d "{\"data\": {\"task\": \"${{ needs.assert-project-membership.outputs.task_id }}\"}}"
