Revert "Set up tmate on sync_end_to_end.yml"
This reverts commit c1171cb88ba14810070d4993e0084ebfe2004a12.

diff --git a/.github/workflows/sync_end_to_end.yml b/.github/workflows/sync_end_to_end.yml
--- a/.github/workflows/sync_end_to_end.yml
+++ b/.github/workflows/sync_end_to_end.yml
@@ -14,6 +14,8 @@ jobs:
       matrix:
         runner: [macos-13-xlarge, macos-14-xlarge]
 
+    timeout-minutes: 60
+
     steps:
     - name: Check out the code
       uses: actions/checkout@v4
@@ -58,7 +60,76 @@ jobs:
     - name: Select Xcode
       run: sudo xcode-select -s /Applications/Xcode_$(<.xcode-version).app/Contents/Developer
 
-    - name: Setup tmate session
-      uses: mxschmitt/action-tmate@v3
+    - name: Create test account for Sync and return the recovery code
+      uses: duckduckgo/sync_crypto/action@main
+      id: sync-recovery-code
       with:
-        limit-access-to-actor: true
+        debug: true
+
+    - name: Build Sync e2e tests
+      run: |
+        set -o pipefail && xcodebuild build-for-testing \
+          -scheme "Sync End-to-End UI Tests" \
+          -configuration Review \
+          -derivedDataPath DerivedData \
+          -skipPackagePluginValidation \
+          -skipMacroValidation \
+        | tee xcodebuild.log \
+        | xcbeautify
+
+    - name: Run UI Tests
+      env:
+        CODE: ${{ steps.sync-recovery-code.outputs.recovery-code }}
+      run: |
+        defaults write com.duckduckgo.macos.browser.review sync.environment Development
+        defaults write com.duckduckgo.macos.browser.review moveToApplicationsFolderAlertSuppress 1
+        defaults write com.duckduckgo.macos.browser.review onboarding.finished -bool true
+        set -o pipefail && xcodebuild test-without-building \
+          -scheme "Sync End-to-End UI Tests" \
+          -configuration Review \
+          -derivedDataPath DerivedData \
+          -skipPackagePluginValidation \
+          -skipMacroValidation \
+          -test-iterations 2 \
+          -retry-tests-on-failure \
+        | tee -a xcodebuild.log \
+        | tee ui-tests.log
+
+    - name: Prepare test report
+      if: always()
+      run: |
+        xcbeautify --report junit --report-path . --junit-report-filename ui-tests.xml < ui-tests.log
+
+    - name: Publish tests report
+      uses: mikepenz/action-junit-report@v4
+      if: always() # always run even if the previous step fails
+      with:
+        check_name: "Test Report ${{ matrix.runner }}"
+        report_paths: ui-tests.xml
+
+    - name: Upload logs when workflow failed
+      uses: actions/upload-artifact@v4
+      if: failure() || cancelled()
+      with:
+        name: "BuildLogs ${{ matrix.runner }}"
+        path: |
+          xcodebuild.log
+          DerivedData/Logs/Test/*.xcresult
+          ~/Library/Logs/DiagnosticReports/*
+        retention-days: 7
+
+  notify-failure:
+    name: Notify on failure
+    if: ${{ always() && github.event_name == 'schedule' && (needs.sync-end-to-end-tests.result == 'failure' || needs.sync-end-to-end-tests.result == 'cancelled') }}
+    needs: [sync-end-to-end-tests]
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Create Asana task when workflow failed
+      uses: duckduckgo/native-github-asana-sync@v1.1
+      with:
+        action: create-asana-task
+        asana-pat: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        asana-project: ${{ vars.MACOS_APP_DEVELOPMENT_ASANA_PROJECT_ID }}
+        asana-task-name: GH Workflow Failure - Sync End-to-End Tests
+        asana-task-description: The Sync end-to-end workflow has failed. See https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
