Update tag_release to not fail on failed merge/delete

diff --git a/.github/workflows/tag_release.yml b/.github/workflows/tag_release.yml
--- a/.github/workflows/tag_release.yml
+++ b/.github/workflows/tag_release.yml
@@ -87,6 +87,7 @@ jobs:
     - name: Merge to base branch
       id: merge
       if: ${{ env.prerelease == 'true' }}
+      continue-on-error: true
       uses: actions/github-script@v7
       with:
         github-token: ${{ secrets.GHA_ELEVATED_PERMISSIONS_TOKEN }}
@@ -101,6 +102,7 @@ jobs:
     - name: Delete release branch
       id: delete
       if: ${{ env.prerelease == 'false' }}
+      continue-on-error: true
       env:
         GH_TOKEN: ${{ github.token }}
       run: |
@@ -112,7 +114,9 @@ jobs:
         GH_TOKEN: ${{ github.token }}
         PROMOTED_TAG: ${{ steps.create-tag.outputs.promoted-tag }}
         TAG: ${{ steps.create-tag.outputs.tag }}
+        MERGE_OR_DELETE_FAILED: ${{ (steps.merge.outcome == 'failure') || (steps.delete.outcome == 'failure') }}
       run: |
+        echo "MERGE_OR_DELETE_FAILED=${MERGE_OR_DELETE_FAILED}" >> $GITHUB_ENV
         echo "TAG=$TAG" >> $GITHUB_ENV
         if [[ "${prerelease}" == "true" ]]; then
           DMG_VERSION=${TAG//-/.}
@@ -139,7 +143,7 @@ jobs:
         fi
 
     - name: Set up Asana templates
-      if: failure()
+      if: failure() || ${{ env.MERGE_OR_DELETE_FAILED }}
       id: asana-failure-templates
       run: |
         if [[ ${{ steps.create-tag.outputs.tag-created }} == "true" ]]; then
@@ -162,7 +166,7 @@ jobs:
 
     - name: Create Asana task on failure
       id: create-task-on-failure
-      if: failure()
+      if: failure() || ${{ env.MERGE_OR_DELETE_FAILED }}
       uses: ./.github/actions/asana-create-action-item
       with:
         access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
@@ -170,7 +174,7 @@ jobs:
         template-name: ${{ steps.asana-failure-templates.outputs.task-template }}
 
     - name: Report failure
-      if: failure()
+      if: failure() || ${{ env.MERGE_OR_DELETE_FAILED }}
       uses: ./.github/actions/asana-log-message
       env:
         ASSIGNEE_ID: ${{ steps.create-task-on-failure.outputs.assignee-id }}
