Move reporting success to tag and merge

diff --git a/.github/workflows/tag_and_merge.yml b/.github/workflows/tag_and_merge.yml
--- a/.github/workflows/tag_and_merge.yml
+++ b/.github/workflows/tag_and_merge.yml
@@ -80,21 +80,20 @@ jobs:
 
     - name: Get Asana automation subtask
       id: get-automation-subtask
-      if: failure() && env.asana-task-url
       uses: ./.github/actions/asana-get-release-automation-subtask-id
       with:
         access-token: ${{ secrets.ASANA_ACCESS_TOKEN }}
         task-url: ${{ env.asana-task-url }}
 
     - name: Create Asana task on failed merge
-      if: failure() && env.asana-task-url
+      if: failure()
       env:
         ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
         ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
         TASK_NAME: "Merging ${{ env.branch }} to ${{ env.base-branch }} failed"
         TASK_BODY: "The ${{ steps.create-tag.outputs.tag }} release has been successfully tagged and published in GitHub releases,
           but merging to ${{ env.base-branch }} failed. Please resolve conflicts and merge ${{ env.branch }} to ${{ env.base-branch }} manually."
-        TASK_ID: ${{ steps.get-automation-subtask.outputs.task-id }}
+        TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
         WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
       run: |
         return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/subtasks" \
@@ -114,5 +113,45 @@ jobs:
 
         if [ $return_code -ne 201 ]; then
           echo "::error::Failed to create Asana task"
+          exit 1
+        fi
+
+    - name: Re-add release task owner to Automation task
+      if: success()
+      env:
+        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        ASSIGNEE_ID: ${{ steps.get-automation-subtask.outputs.assignee-id }}
+        TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
+      run: |
+        return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/addFollowers" \
+          -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
+          -H 'content-type: application/json' \
+          --write-out '%{http_code}' \
+          --output /dev/null \
+          -d "{ \"data\": { \"followers\": [ \"${ASSIGNEE_ID}\" ] } }")
+
+        if [ $return_code -ne 200 ]; then
+          echo "::error::Failed to add a collaborator to the Asana task"
+          exit 1
+        fi
+
+    - name: Report success
+      if: success()
+      env:
+        ASANA_ACCESS_TOKEN: ${{ secrets.ASANA_ACCESS_TOKEN }}
+        TASK_ID: ${{ steps.get-automation-subtask.outputs.automation-task-id }}
+        TASK_BODY: "New internal build is ready. Repository is tagged with ${{ steps.create-tag.outputs.tag }} tag.
+          ${{ env.branch }} branch has been sucessfully merged to ${{ env.base-branch }}."
+        WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      run: |
+        return_code=$(curl -fLSs "https://app.asana.com/api/1.0/tasks/${TASK_ID}/stories" \
+          -H "Authorization: Bearer ${ASANA_ACCESS_TOKEN}" \
+          -H 'content-type: application/json' \
+          --write-out '%{http_code}' \
+          --output /dev/null \
+          -d "{ \"data\": { \"text\": \"${TASK_BODY}\n\nWorkflow URL: ${WORKFLOW_URL}\" } }")
+
+        if [ $return_code -ne 201 ]; then
+          echo "::error::Failed to add a comment to the Asana task"
           exit 1
         fi
